server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: netfly-demo
    static_configs:
      - targets:
          - localhost
        labels:
          job: netfly-demo
          __path__: /var/log/demo/*.log
    pipeline_stages:
      - json:
          expressions:
            project: project
            env: env
            service: service
            level: level
            log_type: log_type
            trace_id: trace_id
            message: message
      - labels:
          project:
          env:
          service:
          level:
          log_type:
